version: "3.8"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: backend
    image: backend-django
    build:
      context: ./backend
      dockerfile: Dockerfile

    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/app/backend/
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env.dev
    restart: unless-stopped
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app/frontend"
      - "/app/frontend/node_modules"
    ports:
      - 3000:3000
    restart: unless-stopped

    stdin_open: true
    tty: true

    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
