# Generated by Django 3.1.2 on 2020-10-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201022_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
