# Generated by Django 3.1.2 on 2020-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20201027_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
