# Generated by Django 3.1.2 on 2020-10-27 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
