# Generated by Django 3.1.2 on 2020-11-18 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_auto_20201106_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiztakers',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_takers', to='quiz.quiz'),
        ),
    ]
