# Generated by Django 3.1.3 on 2020-12-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_auto_20201201_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='training',
            field=models.BooleanField(default=False),
        ),
    ]
