# Generated by Django 3.1.4 on 2020-12-13 15:34

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_auto_20201210_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=quiz.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=255, verbose_name='Question'),
        ),
    ]
