# Generated by Django 3.1.4 on 2020-12-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_auto_20201213_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Question'),
        ),
    ]
