# Generated by Django 3.1.4 on 2020-12-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20201213_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
